### ISSUE TITLE
Wunsch: Sortierte Ausgabe der Klassen im Inhaltselement/Artikel

### ISSUE THREAD

**Issue by githuppi** [xprojects-de/contao-classes#4]
<img width="348" alt="image" src="https://github.com/xprojects-de/contao-classes/assets/24605762/b0257d61-bcd0-4212-8d73-3c4269624488">

Ist es möglich auch die Ausgabe der Klassen im Inhaltselement bzw. Artikel zu sortieren?

In meinem angehängten Beispiel ist das leider nicht der Fall, im Backend Modul hingegen schon.

Vielen Dank für eine Info dazu.

**Comment by xprojects-de** [comment]
Servus,

ja das ist schon denkbar, aber dann müsste man im Backend auch eine Sortierung einführen. Die werden nach dem Titel aufsteigen sortiert angezeigt, habt aber nichts mit der Sortierung im Frontend zu tun. Im Frontend werden die Elemente derzeit so genommen in welcher Reihenfolge sie angelegt wurden.

Wenn man eine SOrtierung möchte sollte man denke ich im Backend auch sortieren können...
Das müsste man halt implementieren :-)

**Comment by githuppi** [comment]
Hallo,

vielen Dank für die Antwort. Es geht mir im speziellen um die Ausgabe im Backend. Derzeit werden die ausgegebenen Klassen im Backend-Modul `Alpdesk-Klassen` alphabetisch sortiert. 

Lege ich während der Erstellung einer Website dort mehrere Klassen an und im weiteren Verlauf kommen weitere dazu (in meinem Bsp. ab [Text] zentriert) ist die Ausgabe über `spezielle Klassen` im Inhaltselement durcheinander (scheinbar sind die zuletzt erstellten Klassen am Ende der Liste einsortiert).

Lege ich auf diesem Wege viele Klassen nachträglich an (beim Erstellen der Website) habe ich im Artikel/Inhaltselement eine unsortierte Liste, die im Nachgang für einen Redakteur sehr verwirrend wirken kann. Daher die Frage ob es möglich ist die Liste im Reiter `spezielle Klassen` im Inhaltselement/Artikel standardmäßig alphabetisch auszugeben:

```
[Layout] Teaserfläche im Spaltenset
[Text] zentriert
[Überschrift] <h2> Größe wie <h1>
[Überschrift] <h3> Primary color
[Überschrift] Weiß 
… usw.
```

**Comment by xprojects-de** [comment]
Servus, 

das ist kein Problem und lässt ich einfach realisieren.
Nur hier: https://github.com/xprojects-de/contao-classes/blob/main/src/Resources/contao/dca/tl_article.php#L45 und heir: https://github.com/xprojects-de/contao-classes/blob/main/src/Resources/contao/dca/tl_content.php#L51 ein orderby als Parameter mit übergeben...

Wenn du willst kannst du es gerne selber per PullRequest versuchen :-) Sonst mache ich es die Tage mal...

Grüße

**Comment by githuppi** [comment]
Hallo,

danke für den Richtungsweiser. Ich habe jetzt in der /dca/tl_article.php und /dca/tl_content.php die folgende Zeile ergänzt:

`
$options = [
  		'order' => 'title ASC'
	];
        $classObjects = AlpdeskClassesModel::findAll($options);`
        
Nach dem Löschen des Caches im Manager funktioniert die Ausgabe nun wie gewünscht. Das mit dem Einbauen überlasse ich gern dir als Entwickler. 

Vielen Dank für die Hilfe hier!

**Comment by xprojects-de** [comment]
@githuppi Danke für deine Mühe.
Ist released in 1.0.3
See https://github.com/xprojects-de/contao-classes/pull/5
